---
kind: pipeline
type: docker
name: buildx

platform:
  os: linux
  arch: amd64

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock

steps:
- name: build
  image: alexviscreanu/buildx
  commands:
    - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
    - docker buildx create --use --name amd-arm
    - docker buildx inspect --bootstrap
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 $DRONE_REPO .
    - docker buildx rm amd-arm
  volumes:
    - name: docker_socket
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
        from_secret: docker_username
    DOCKER_PASSWORD:
        from_secret: docker_password

---
kind: pipeline
type: docker
name: notification

trigger:
  status:
  - success
  - failure

platform:
  os: linux
  arch: amd64

steps:
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_user

depends_on:
  - buildx
